name: Build App

on:
  workflow_dispatch:
    inputs:
      v-tag:
        description: Version tag without the 'v'
        required: true

jobs:

  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
        
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get commit count
        run:  |
          echo "Working Path: ${Env:GITHUB_WORKSPACE}"
          echo "COMMIT_COUNT=$(git rev-list --count main)" >> $Env:GITHUB_ENV
          
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.0.5
      - name: Restore nuget packages
        run: nuget restore CubariHelper\CubariHelper.csproj
        
      - name: Build Binary
        shell: cmd
        run: call .\Build.cmd
      - name: Build Artifact
        shell: cmd
        run: call .\ArtifactBuild.cmd
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.v-tag }}
          release_name: CubariHelper v${{ github.event.inputs.v-tag }} r${{ env.COMMIT_COUNT }}
          body: |
            [Release notes here](https://github.com/Jacekun/CubariHelper/blob/main/_docs/version_log.md)
          draft: false
          prerelease: false
          
      - name: Upload Release Asset (Any CPU)
        id: upload-release-asset-any-cpu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./CubariHelper_AnyCPU.zip
          asset_name: CubariHelper_Jacekun.ZIP
          asset_content_type: application/zip
